### ISSUE TITLE
Sync users with dev

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/chaingear#24]

**Comment by tomarcafe** [comment]
каких конкретно?

**Comment by 21xhipster** [comment]
Ты сам просил напомнить!

**Comment by tomarcafe** [comment]
ок :) ну там я так п только ваш тяжолый сатошифонд надо?

**Comment by vitalylvov** [comment]
@tomarcafe Если собрался переносить из дева в прод сатоши-фонд, то уже не надо, я его заново завел и сейчас там правильные цифры

**Comment by tomarcafe** [comment]
хорошо
