### ISSUE TITLE
Goldmint 17 Sept

### ISSUE THREAD

**Issue by a-kov** [cyberFund/chaingear#426]
@Protectorofcode Check Goldmint for compliance and add to site

17 Sept
Screening report done
https://medium.com/@blocksharks/goldmint-ico-legal-review-of-some-aspects-of-the-white-paper-by-blocksharks-46cbbd671367
N

**Comment by Protectorofcode** [comment]
@a-kov This project not suitable for cyber•Fund.
I dont find platform code in git hub. Only contracts code. There is no technical part in the whitepaper.
