### ISSUE TITLE
dharma.io - 2018

### ISSUE THREAD

**Issue by a-kov** [cyberFund/chaingear#452]
Check for compliance. If ok - prepare content and add to site

**Comment by trummax** [comment]
no ICO announcement yet

https://twitter.com/dharmaprotocol

**Comment by trummax** [comment]
https://blog.dharma.io/dharma-an-open-protocol-for-generic-tokenized-debt-agreements-9a4e6a4e6fc0

**Comment by trummax** [comment]
No token sale

https://blog.dharma.io/dharma-isnt-currently-doing-a-token-sale-and-here-s-why-afa04e78247b
