### ISSUE TITLE
Mercury Protocol - 25 Oct - open code, contract to come soon

### ISSUE THREAD

**Issue by a-kov** [cyberFund/chaingear#455]
@Protectorofcode - Add ICO dates
Only wp, no tech spec as of 5 Oct - waiting for more

**Comment by a-kov** [comment]
E-mail sent, waiting for ICO address

**Comment by a-kov** [comment]
Ответ от команды: We'll be open sourcing the Mercury Protocol soon, and will publish the GMT contract once we finish our security audit in the next few days.

**Comment by trummax** [comment]
Due dil done by @cyberanalytics freelance writer
https://golos.io/vox-populi/@cyberanalytics/obzor-ico-proekta-mercury-protocol
