### ISSUE TITLE
Leverj - 7 Nov - Open source/contract to come

### ISSUE THREAD

**Issue by a-kov** [cyberFund/chaingear#507]
Check for compliance. If ok - prepare content for site and add to site

**Comment by a-kov** [comment]
Code: will be open except some things like private keys
Waiting for ICO address / contract code

**Comment by trummax** [comment]
@ninjascant prepare content for site 
due dil by @cyberanalytics bidding

https://leverj.io/
Open source code https://github.com/coinpit

**Comment by ninjascant** [comment]
Added to chaingear

**Comment by trummax** [comment]
published on https://golos.io/vox-populi/@cyberanalytics/obzor-ico-proekta-leverj

**Comment by trummax** [comment]
prepared by https://golos.io/@volodya633

**Comment by trummax** [comment]
https://golos.io/vox-populi/@cyberanalytics/obzor-ico-proekta-leverj
