### ISSUE TITLE
Quantstamp - 12/11

### ISSUE THREAD

**Issue by a-kov** [cyberFund/chaingear#579]
Prepare content for site

**Comment by a-kov** [comment]
Listed

**Comment by trummax** [comment]
ann: https://medium.com/quantstamp/quantstamp-token-sale-announcement-5b6ae03e73a8

**Comment by trummax** [comment]
due dill by golos outsourcing (bidding from 08/11 to 12/11)

**Comment by ninjascant** [comment]
Closed since Chaingear database moved to the new repo
