### ISSUE TITLE
True Flip Markets

### ISSUE THREAD

**Issue by gamedevsam** [cyberFund/chaingear#603]
The markets tab still shows up empty: https://cyber.fund/system/True_Flip_Lottery

Does Cyber.Fund use an old version of ChainGear API?

I see the aliases show up properly in the [generated JSON](http://chaingear.cyber.fund/chaingear.json).

**Comment by 21xhipster** [comment]
To be honest this tab has never work good :-( We decide to not support this version of site and developing brand new.

**Comment by gamedevsam** [comment]
Sounds good, feel free to close this issue. Looking forward to see the new version!
