### ISSUE TITLE
Andaction

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/chaingear#610]
https://drive.google.com/file/d/0B8sboM-31m1kSF94akhzc3B2WEk/view
andaction.io

**Comment by 21xhipster** [comment]
Ребята попросили сказать что я думаю об этом проекте. Вот что получилось:

> The hacker finds a vulnerability in Bitcoin and uses it to steal 165 million dollars and catch Satoshi’s eye.

- Чушь какая-то а не сюжет...  Писал чувак нихуя не понимающий в сути технологии. Ни копейки под такой сюжет не дам ей богу.

ARTIFICIAL INTELLIGENCE D.E.U.S. - вообще не понимаю причем тут болкчейн технология и как это будет связано. Честно выглядет как либо (1) нереализуемый маркетингбулщит, либо (2) пропприетарная технология реализованная централизованно которая не будет иметь отношения к внутренней стоимости токенов.

Proof-of-Watch consensus - тоже полное дерьмеще. Если говорите про Proof то нужно математическое доказательство. 

Че было бы круто сделать, чтобы сделать из этого проекта норм штуку:
- сделать в бумаге акцент на разработке проктола (1) (никому в крипте не интересно спонсировать сьемку фильма). ДОПОЛНЕНИЕМ в бумаге могут быть раскрыты 3 штуки: (2) кино, (3) приложение для юзеров и (4) приложение для профессионалов. Но акцент дб на протоколе. 
- Усилить логику и экономику протокола (1). Сейчас видно что промоматериал (бумагой это не назовешь) писал человек нихуя в эттом не сведуюищй. Соответственно криптоинвесторов профессионалов - не ждите. Будет масса тупых баранов, которые вам мало что дадут кроме гемороя. Самый близкий кейс из видованных мною, который можно адаптировать к Вашему и который грамотно написан это Opus https://opus-foundation.org/whitepaper.pdf. Используйте его.
- (2) сценарий первого кейса на платформе привести в соответствие с реальностью. На данный момент выглядит как голивудская чушь. Если профи фильм обосрут, больше чем 6 на IMDB ему не светит.
- (3) и (4) Вычистить из бумаги булщит про искуственный интеллект и нейромаркетинг либо дать ясно понять, что эти два направления будут использоваться для усиления (3) централизованного юзерского приложения и (4) приложения для профессионалов
- ICO и Pre-ICO. Структурирование ICO, Pre_ICO с разницей в 3 месяца - какая логика? Собрать немного денег, чтобы собрать денег побольше под бумагу состоящую из маркетингового булщита? Вот ей богу не круто. Лучше собирете 1 млн на разработку протокола и после того, как его оттестируете (6-9 месяцев) проведите ICO. Тогда вы (а) максимизурете ревенью от ICO. Сейчас 75 млн выглядят неадекватными и (b) соберете реально хорошую аудиторию грамотных инвесторов, а не баранов

**Comment by ninjascant** [comment]
Closed since Chaingear database moved to the new repo
