### ISSUE TITLE
Raiden Network - 18 Oct

### ISSUE THREAD

**Issue by a-kov** [cyberFund/chaingear#614]
@trummax Prepare content for site + due dil

https://github.com/raiden-network/raiden-token/blob/master/contracts/auction.sol
Address requested
Open source code

ICO date to be confirmed

**Comment by 21xhipster** [comment]
Hi prioroty

**Comment by trummax** [comment]
https://blog.cyber.fund/raiden-network-ico-report-974d663e8e11
