### ISSUE TITLE
Ocean protocol

### ISSUE THREAD

**Issue by a-kov** [cyberFund/chaingear#660]
Monitor for more info https://oceanprotocol.com/

**Comment by trummax** [comment]
Check for compliance and if ok - collect data and add to site

ICO TBA

**Comment by trummax** [comment]
monitor for ICO announcement

**Comment by trummax** [comment]
https://github.com/oceanprotocol empty

**Comment by trummax** [comment]
https://oceanprotocol.com/#papers

**Comment by trummax** [comment]
ICO is over
