### ISSUE TITLE
Blockstack - 13 Nov - open-source, contract to come

### ISSUE THREAD

**Issue by trummax** [cyberFund/chaingear#685]
@ninjascant prepare content for site
@Masterline999  due dil draft
 
https://blockstack.org/
Open source code https://github.com/blockstack

**Comment by ninjascant** [comment]
Added to chaingear

**Comment by trummax** [comment]
драфт https://docs.google.com/document/d/1ofBoeQG8ZXCjlEaziP1tQh6pS8_1uO0j9qeZohi-lWk/edit#
