### ISSUE TITLE
Rename Objects and Arrays

### ISSUE THREAD

**Issue by vitalylvov** [cyberFund/chaingear#7]
Rename Oblects:
```
name = system
blockchain_id = genesis_id
short_description = headline
CoinMarketCap = coinmarketcap
blockTime = block_time
reward = block_reward
halfingCycle = halfing_cycle
total = total_tokens
premine = premine_tokens
difficultyCycle = difficulty_cycle
txsConfirm = txs_confirm
mintConfirm = mint_confirm
```
Move between Arrays and rename Objects:
```
symbol = token.token_symbol
metrics.rating = ratings.rating_cyber
metrics.consensus = consensus.consensus_name
metrics.algo = consensus.hashing
metrics.status = descriptions.state
metrics.type = descriptions.tags
metrics.hashtag = descriptions.hashtag
metrics.announce = events.announcement
metrics.genesis = events.genesis
```

Add Objects:
```
token.token_name
descriptions.system_type
consensus.consensus_type
links.type
```

Change Object to Array:
```
dependencies = [dependencies]
```

Rename Array:
```
metrics = specs
```

**Comment by tomarcafe** [comment]
а смысл объект на массив менять?

**Comment by tomarcafe** [comment]
ну ок, проверяйте.

**Comment by tomarcafe** [comment]
вообще, по папочкам можно и не сейчас разбирать.
далее. у папки имя - имя системы будет, так?

**Comment by 21xhipster** [comment]
Да. У папки имя - Имя системы.
Ну вообще можно конечно папочки сейчас не делать. Еще гемор прицепим. Отдельной задачей
Вот еще список за
убрать "source": "cyberFund”,
CurrencyName => token.token_name

**Comment by tomarcafe** [comment]
!!!! также. из того что я вижу: папки с томлами придётся переименовывать вручную, в случае если имя поменяется.

т.е.: если мы пытаемся добираться до контента через `https://gihub/ch_g/<system>/system_icon.png - и system соответствует chainger имени - то когда chaingear имя поменяется - необходимо будет переименовать и папку, в которой эта система обитает - и файл.

**Comment by tomarcafe** [comment]
не, там дел на минуту. я так понимаю, имена меняться будут в совсем уж аварийных случаях так что не страшно.

**Comment by 21xhipster** [comment]
@vitalylvov Don't forget to monitor and close opened issues
