### ISSUE TITLE
Tokenbnk - 30/11

### ISSUE THREAD

**Issue by trummax** [cyberFund/chaingear#731]
Comliance - OK
https://github.com/TokenBnk/

**Comment by trummax** [comment]
due dill by golos outsourcing (bidding from 08/11 to 12/11)

**Comment by trummax** [comment]
due dill by golos outsourcing failed (no bids)

@Masterline999 due dill to do, draft till 25/11

**Comment by ninjascant** [comment]
Closed since Chaingear database moved to the new repo
