### ISSUE TITLE
Fix first price and date

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/chaingear#74]
- First Blood
- Iconomi
- Zcash

**Comment by vitalylvov** [comment]
FirstBlood - https://github.com/cyberFund/chaingear/commit/faab590c57e026d466f21c5c39b67543d1555206
Iconomy - https://github.com/cyberFund/chaingear/commit/3df19d5903bcf0d75892fbcd28f718e11af90a16
ZCash - https://github.com/cyberFund/chaingear/commit/47d909a712cc20884dce45d9ff947f821a7a419d
