### ISSUE TITLE
Nebulas - TBA

### ISSUE THREAD

**Issue by trummax** [cyberFund/chaingear#740]
open source https://github.com/nebulasio
monitor for ICO Date

**Comment by trummax** [comment]
Until Nov 15, 2017, the supply in circulation is 5,000,000 NAS (Nebulas token). It came from the influential investors’ sales on June 28, 2017. Nebulas team have not raised funds in any other way

**Comment by ninjascant** [comment]
Closed since Chaingear database moved to the new repo
