### ISSUE TITLE
omega.one - 2018

### ISSUE THREAD

**Issue by trummax** [cyberFund/chaingear#742]
monitor for ICO ann

some details (inlcuding presale): https://media.consensys.net/omega-one-a-balance-sheet-solution-for-crypto-liquidity-647a47ff1347

**Comment by trummax** [comment]
telegram: 
Omega community,

An email spoof went out recently soliciting ETH from an omega.one address. This is a scam. As a reminder, we will never solicit ETH over email and per our announcement last week we have delayed our pre sale. 

Any communications about our token sale process, once it reopens in 2018, will be PGP signed, and verifiable on Netkey, with a copy of that email hosted on omega.one domain. 

We must keep in mind the unfortunate reality that any high profile project will have scammers trying to profit alongside it. We thank you for your vigilance and continued support of our project.

**Comment by ninjascant** [comment]
Closed since Chaingear database moved to the new repo
