### ISSUE TITLE
Непонятно как они оказались в Радаре (внизу)

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/chaingear#89]
<img width="1278" alt="screen shot 2017-05-18 at 11 57 48" src="https://cloud.githubusercontent.com/assets/410789/26197135/7ef83400-3bc1-11e7-8ab8-fad448b9cc40.png">

**Comment by 21xhipster** [comment]
Необходимо поправить ВСЕ проекты у которых время жизни больше 10 тысяч дней.

**Comment by vitalylvov** [comment]
3d7483b4f3ca7ac3d04e24fff8ac9c1ce519cd14
