### ISSUE TITLE
Change Button Placement (Put to the Header)

### ISSUE THREAD

**Issue by MarkLouren** [cyberFund/chaingear#919]
**Preferable Place**: http://joxi.ru/l2Zl35NFwnanzr

**Comment by abitrolly** [comment]
It is better to discuss it at https://github.com/cyberFund/cyber.fund/issues/466

**Comment by 21xhipster** [comment]
Not relevant

**Comment by abitrolly** [comment]
Fixed by @tomarcafe in https://github.com/cyberFund/cyber.fund/commit/8357c40c912c40ba050512ccd7e3b9234cfbb0c5

![image](https://user-images.githubusercontent.com/8781107/37253083-c7038be4-253d-11e8-8bff-04d6200a1145.png)
