### ISSUE TITLE
https://cyber.fund/EMC

### ISSUE THREAD

**Issue by abitrolly** [cyberFund/chaingear#96]
UX may be better. Today's user story. I want to check EMC data fast. Right now I have to:

1. type cyber.fund URL
2. click search form
3. wait for EMC to appear (slow)
4. click EMC name or hit Enter

What I want:

1. type cyber.fund/EMC URL

---

Implementation will require:

1. ensure that URL handling is case sensitive
2. assume all root uppercase paths are coin names
3. generate redirects / proxy pages for every supported coin name
4. generate search form / redirect for unsupported coin name (coin not found)
5. generate search form / redirect for missing page (page not found, log referrer)

**Comment by 21xhipster** [comment]
Not relevant
