### ISSUE TITLE
Setup link checker

### ISSUE THREAD

**Issue by abitrolly** [cyberFund/chaingear#98]
QA. Another story from today. Went to check what BTCD is and landed on spammed domain through cyber.fund links (#99).

The site was down for more than a year, so it could help if there was link autocheck for every PR / commit + every few days will ensure data quality of our dataset. Also should check for squatted domains.

Also, could be a good marketing point like "data quality feedback loop", which is tied to Cybernetics.

**Comment by abitrolly** [comment]
Feature creeping - maintain DB of checked links somewhere.

**Comment by ninjascant** [comment]
Closed since Chaingear database moved to the new repo
